---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action üß™'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      # Needed to locally invoke the action when testing
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          # No need to checkout the local repository twice
          no_checkout: true
          branch_name: 'linting-test'

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Config download]"
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          config_url: 'https://raw.githubusercontent.com/lfreleng-actions/test-python-project/refs/heads/main/resources/pre-commit-config.yaml'

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'lfreleng-actions/test-python-project'
          path: 'test-python-project'

      # Deliberate failure; linting will not pass run against default branch
      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Fail/test-python-project]"
        id: failure
        uses: ./
        with:
          path_prefix: 'test-python-project'
          no_checkout: true
        continue-on-error: true

      - name: 'Error if step above did NOT fail'
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo 'Error: previous test step did NOT fail ‚ùå'
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Pass/test-python-project]"
        uses: ./
        with:
          # No need to checkout the local repository twice
          no_checkout: true
          path_prefix: 'test-python-project'
          branch_name: 'linting-test'
